version: "3.1"
services:
    mysql:
        image: mysql:5.7
        container_name: easyappointments-database
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=easyappointments
        ports:
            - "8010:3306"
    server:
        build: ./server
        image: easyappointments-server:v1
        container_name: easyappointments-server
        ports:
            - "8011:80"
        volumes:
            - /home/oscar/Documentos/docker/easyappointments:/var/www/html
            - /home/oscar/Documentos/docker/easyappointments/server/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini